[package]
name = "graphql-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.16.0"
juniper_warp = "0.8.0"
tokio =  { version = "1.37.0", features = ["full"] }
warp = "0.3.6"
