name: graphql-example-angular-rust

services:
  frontend:
    image: titaniumit/graphqlexample-angular:latest
    build: ./frontend/angular/
    networks:
      - default
    ports:
      - "4200:80"
    deploy:
      mode: replicated
      replicas: 1

  backend:
    image: titaniumit/graphqlexample-rust:latest
    build: ./backend/rust/
    networks:
      - default
    ports:
      - "7265:8080"
    deploy:
      mode: replicated
      replicas: 1

